PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX : <http://dbpedia.org/resource/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX yago: <http://dbpedia.org/class/yago/>
PREFIX dbpedia-owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbpprop: <http://dbpedia.org/property/>
SELECT DISTINCT ?name ?population ?populationTotal ?popRecense ?popEstimation ?area ?density WHERE {
  ?x a yago:EuropeanCountries .
  ?x rdfs:label ?name .
   filter(langMatches(lang(?name),"fr"))

  OPTIONAL{?x dbpprop:populationDensityKm ?density }
  OPTIONAL{?x dbpprop:areaKm ?area}
  OPTIONAL{?x dbpedia-owl:populationTotal ?populationTotal }
  OPTIONAL{?x dbpprop:populationCensus ?popRecense }
  OPTIONAL{?x dbpprop:populationEstimate ?popEstimation }

  BIND(
    IF(bound(?populationTotal),
      ?populationTotal,
      IF(bound(?popRecense),
        ?popRecense,
        IF(bound(?popEstimation),
          ?popEstimation,
          xsd:integer(?area * ?density)
        )


      )
    )
  as ?population)
}order by asc (?name)